### ISSUE TITLE
Add option for register classes by interface

### ISSUE THREAD

**Issue by martinknor** [ublaboo/directory-register#3]
It would be nice if you can make something like this

```
autoRegister:
    dirs: [
        IFormFactory: %appDir%
    ]
```

what do you think?
